"""Case corpus, scoring and null models (PLAN E.3, E.4)."""

from fatpitch.cases.holdout import HoldoutError
from fatpitch.cases.nulls import (
    AlwaysRiskOn,
    FedDirectionOnly,
    NoChangeTilt,
    Persistence,
    PriorTiltPersistence,
    Trend12m,
    default_nulls,
    tilt_baselines,
)
from fatpitch.cases.schema import (
    Case,
    CaseError,
    Corpus,
    Targets,
    ThesisTarget,
    Window,
    load_case,
    load_corpus,
    parse_case,
    turning_point_ids,
)
from fatpitch.cases.scoring import (
    CaseScore,
    Engine,
    GateResult,
    PairedResult,
    PermutationResult,
    Prediction,
    PredictionCache,
    Result,
    ScoringRule,
    aggregate,
    margin_over_best_null,
    paired_gate,
    paired_sign_flip_test,
    permutation_test,
    run,
    score_case,
)

__all__ = [
    "AlwaysRiskOn",
    "Case",
    "CaseError",
    "CaseScore",
    "Corpus",
    "Engine",
    "FedDirectionOnly",
    "GateResult",
    "HoldoutError",
    "NoChangeTilt",
    "PairedResult",
    "PermutationResult",
    "Persistence",
    "Prediction",
    "PredictionCache",
    "PriorTiltPersistence",
    "Result",
    "ScoringRule",
    "Targets",
    "ThesisTarget",
    "Trend12m",
    "Window",
    "aggregate",
    "default_nulls",
    "load_case",
    "load_corpus",
    "margin_over_best_null",
    "paired_gate",
    "paired_sign_flip_test",
    "parse_case",
    "permutation_test",
    "run",
    "score_case",
    "tilt_baselines",
    "turning_point_ids",
]
